# Generated by Django 2.0.1 on 2018-09-19 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('option', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('description_mission', models.TextField()),
                ('description_company', models.TextField()),
                ('type_experience', models.CharField(max_length=100)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('github', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('period', models.DateField(default=datetime.datetime(2018, 9, 19, 13, 23, 4, 455253, tzinfo=utc))),
                ('num_project', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_main', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='personalproject',
            name='technologies',
            field=models.ManyToManyField(to='portfolio.Technology'),
        ),
        migrations.AddField(
            model_name='experience',
            name='tasks',
            field=models.ManyToManyField(to='portfolio.Task'),
        ),
        migrations.AddField(
            model_name='experience',
            name='technologies',
            field=models.ManyToManyField(to='portfolio.Technology'),
        ),
    ]
