# Generated by Django 2.0.1 on 2018-09-18 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalproject',
            name='period',
            field=models.DateField(default=datetime.datetime(2018, 9, 18, 19, 1, 44, 20397, tzinfo=utc)),
        ),
    ]
