# Generated by Django 2.0.1 on 2018-09-19 00:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180918_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalproject',
            name='period',
            field=models.DateField(default=datetime.datetime(2018, 9, 19, 0, 55, 12, 885970, tzinfo=utc)),
        ),
    ]
